#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/getBranch
source "$(dirname "${BASH_SOURCE[0]}")"/toUpperCase

function getSchema() {
  VARIANT=APOLLO_GRAPH_VARIANT_"$(toUpperCase $(getBranch) | tr '-' '_')"
  if [ ! -z "${!VARIANT}" ]; then
    echo "${!VARIANT}"
  else
    case "$BRANCH" in
      main)
        echo production
        ;;
      master)
        echo production
        ;;
      hotfix*)
        echo staging
        ;;
      release*)
        echo staging
        ;;
      develop*)
        echo develop
        ;;
      *)
        echo current
    esac
  fi
}
