#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/getBranch
source "$(dirname "${BASH_SOURCE[0]}")"/toUpperCase

function getSchema() {
  VARIANT=APOLLO_GRAPH_VARIANT_"$(toUpperCase $(getBranch) | tr '-' '_')"
  if [ ! -z "${!VARIANT}" ]; then
    echo "$VARIANT"
  else
    case "$BRANCH" in
      master)
        echo production
        ;;
      hotfix*)
        echo staging
        ;;
      release*)
        echo staging
        ;;
      develop*)
        echo develop
        ;;
      feature*)
        echo current
        ;;
      bugfix*)
        echo current
        ;;
      *)
        echo current
    esac
  fi
}
