#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/getBuild

git fetch --all --tags

function getTag() {
  if [ -f ./tag.txt ]; then
    TAG="$(cat ./tag.txt)"
  else
    BUILD=$(getBuild)
    
    TAGS=$(git fetch --all --tags)

    i=1
    TAG="${BUILD}-${i}"

    while [[ $(git tag -l "$TAG") ]]
    do
      i=$(($i + 1))
      TAG="${BUILD}-${i}"
    done
    echo "$TAG" > ./tag.txt
  fi

  echo "$TAG"
}
