#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/getBranch
source "$(dirname "${BASH_SOURCE[0]}")"/getBuild

function getTag() {
  if [ -f ./tag.txt ]; then
    TAG="$(cat ./tag.txt)"
  else
    BUILD=$(getBuild)
    
    git fetch --all --tags

    i=1
    TAG="${BUILD}-${i}"

    while [[ $(git tag -l "$TAG") ]]
    do
      TAG="${BUILD}-${i}"
      i=$(($i + 1))
    done
    echo "$TAG" > ./tag.txt
  fi

  BRANCH=$(getBranch)
  git tag -a "${TAG}" -m "Tag from CI"
  git pull origin "${BRANCH}"
  git push origin "${BRANCH}" --tags
  
  echo "$TAG"
}
