#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/subito-lib-path-resolver
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getTag

TAG=$(getTag)

if [ ! -f ./.dockerinore ]; then
  cp "$CIPATH"/../configs/.dockerinore ./.dockerinore
fi
if [ ! -f ./Dockerfile ]; then
  cp "$CIPATH"/../configs/Dockerfile ./Dockerfile
fi

docker build -t $TAG -f Dockerfile ./dist
docker save --output tmp-image.docker $TAG
