#!/bin/bash
source ./subito-lib-path-resolver
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getTag

TAG=$(getTag)
docker build -t $TAG -f Dockerfile .
docker save --output tmp-image.docker $TAG
