#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/subito-lib-path-resolver
CIPATH=$(subitoLibPathResolver)

cp ./package.json ./dist/package.json
cp ./package-lock.json ./dist/package-lock.json

if [ ! -f ./.yarnclean ]; then
  cp "$CIPATH"/../configs/.yarnclean ./dist/.yarnclean
else
  cp ./.yarnclean ./dist/.yarnclean
fi

cd ./dist

npm ci --omit=dev
if test "$1" != '--simple'; then
  npm install -g node-prune
  node-prune
fi

apt-get install -y yarn

yarn import
yarn autoclean --force

cd ../
