#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/subito-lib-path-resolver
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getGraphqlEndpoint
source "$CIPATH"/helpers/getSchema
source "$CIPATH"/helpers/getShortSlug

bash "$CIPATH"/test-schema

SCHEMA=$(getSchema)
SLUG=$(getShortSlug)
ENDPOINT=$(getGraphqlEndpoint)

SCHEMA=$(getSchema)

if [ -z "${!APOLLO_GRAPH_ID}" ]; then
    echo /!\ Missing env var: APOLLO_GRAPH_ID
fi
cd ./src/
cat graphql/schemas/*.graphql | npx rover subgraph publish "$APOLLO_GRAPH_ID"@"$SCHEMA" --name $SLUG --schema - --routing-url "$ENDPOINT"
cd ../
