#!/bin/bash
# source "$(dirname "${BASH_SOURCE[0]}")"/subito-lib-path-resolver
# CIPATH=$(subitoLibPathResolver)
# source "$CIPATH"/helpers/getBranch
# source "$CIPATH"/helpers/getBuild
# source "$CIPATH"/helpers/getSlug
# source "$CIPATH"/helpers/getTag

# docker load --input ./tmp-image.docker
# BUILD=$(getBuild)
# SLUG=$(getSlug)
# TAG=$(getTag)

# case "$1" in
#   gcr)
#     # Authenticating with the service account key file
#     echo "$GCR_API_KEYFILE" > ./gcloud-api-key.json
#     # Login to google docker hub
#     cat ./gcloud-api-key.json | docker login -u _json_key --password-stdin ${CR_URL}
#     gcloud auth activate-service-account --key-file gcloud-api-key.json
#     gcloud config set project ${CR_PROJECT}
#     ;;
#   *)
#     echo "$CR_PASSWORD" | docker login -u ${CR_USERNAME} --password-stdin ${CR_URL}
# esac

# REGISTRY_URL=${CR_URL}/${CR_PROJECT}
# BRANCH=$(getBranch)
# git tag -a "$TAG" -m "Tag from CI"
# git pull origin "$BRANCH"
# git push origin "$BRANCH" --tags

# IMAGE="$REGISTRY_URL"/"$SLUG":"$TAG"
# IMAGE_LATEST="$REGISTRY_URL"/"$SLUG":"$BUILD"-latest
# docker tag ${TAG} ${IMAGE} 
# docker tag ${TAG} ${IMAGE_LATEST} 
# docker push ${IMAGE}
# docker push ${IMAGE_LATEST}
