#!/bin/bash
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getGraphqlEndpoint
source "$CIPATH"/helpers/getSchema
source "$CIPATH"/helpers/getShortSlug

bash "$CIPATH"/test-schema

SCHEMA=$(getSchema)
SLUG=$(getShortSlug)
ENDPOINT=$(getGraphqlEndpoint)

SCHEMA=$(getSchema)

if [ -z "${!APOLLO_GRAPH_ID}" ]; then
    echo /!\ Missing env var: APOLLO_GRAPH_ID
fi

cat graphql/schemas/*.graphql | npx -p @apollo/rover@latest rover subgraph publish "$APOLLO_GRAPH_ID"@"$SCHEMA" --name $SLUG --schema - --routing-url "$ENDPOINT"
