#!/bin/bash

function subitoLibPathResolver() {
  SOURCE="${BASH_SOURCE[0]}"
  CURRENT="${SOURCE##*/}"
  if [ $CURRENT == .bin ]; then
    echo ../subito-ci/lib
  else 
    # While $SOURCE is a symlink, resolve it
    while [ -h "$SOURCE" ]; do
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$( readlink "$SOURCE" )"
        # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  fi
  echo "$DIR"
}
