#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/subito-lib-path-resolver
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getSchema
source "$CIPATH"/helpers/getShortSlug

SCHEMA=$(getSchema)
SLUG=$(getShortSlug)

if [ -z "${!APOLLO_GRAPH_ID}" ]; then
    echo /!\ Missing env var: APOLLO_GRAPH_ID
fi

cd src/
cat graphql/schemas/*.graphql | npx -p @apollo/rover@latest rover subgraph check "$APOLLO_GRAPH_ID"@"$SCHEMA" --name $SLUG --schema -
cd ../
