#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")"/subito-lib-path-resolver
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getSchema
source "$CIPATH"/helpers/getShortSlug

SCHEMA=$(getSchema)
SLUG=$(getShortSlug)

if [ -z "$APOLLO_GRAPH_ID" ]; then
    echo /!\ Missing env var: APOLLO_GRAPH_ID
    exit 1
fi

cat ./src/graphql/schemas/*.graphql | npx rover subgraph check "$APOLLO_GRAPH_ID"@"$SCHEMA" --name $SLUG --schema -
