#!/bin/bash
CIPATH=$(subitoLibPathResolver)
source "$CIPATH"/helpers/getSchema
source "$CIPATH"/helpers/getShortSlug

SCHEMA=$(getSchema)
SLUG=$(getShortSlug)

if [ -z "${!APOLLO_GRAPH_ID}" ]; then
    echo /!\ Missing env var: APOLLO_GRAPH_ID
fi

cat graphql/schemas/*.graphql | npx -p @apollo/rover@latest rover subgraph check "$APOLLO_GRAPH_ID"@"$SCHEMA" --name $SLUG --schema -
